hosts_map:
  172.16.100.100:
    - vpn.test.trombik.org
strongswan_extra_packages: "{% if ansible_os_family == 'Debian' %}[ 'strongswan-plugin-eap-mschapv2' ]{% else %}[]{% endif %}"
strongswan_config_fragments:
  - name: charon-logging.conf
    content: |
      charon {
        syslog {
          daemon {
            default = 2
          }
          auth {
            default = 2
          }
        }
      }
strongswan_config: |
  charon {
    multiple_authentication=no
    load_modular = yes
    plugins {
      include strongswan.d/charon/*.conf
      eap-peap {
        phase2_method = mschapv2
      }
    }
  }
strongswan_ipsec_secrets:
  no_log: no
  mode: "0600"
  content: |
    carol@strongswan.org : EAP "Ar3etTnp"
strongswan_ipsec_config: |
  config setup

  conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2

  conn vpn
      # my address is not static
      left=%any
      # authenticate me with EAP-MSCHAPv2
      leftauth=eap-mschapv2
      # use this EAP user name when the gateway authenticates me
      eap_identity=carol@strongswan.org
      # assigned by the gateway
      leftsourceip=%config
      leftfirewall=yes
      # assigned by the gateway
      leftdns=%config4
      # gateway address
      right=vpn.test.trombik.org
      # ask the gateway to send its cert
      rightsendcert=yes
      # authenticate the gateway with pubkey
      rightauth=pubkey
      # ... using this CA
      rightca="C=CH, O=strongSwan, CN=strongSwan CA"
      # tunnel all traffic thorough VPN
      rightsubnet=0.0.0.0/0
      auto=add
x509_certificate:
  - name: ca
    state: present
    public:
      path: "{% if ansible_os_family == 'FreeBSD' %}/usr/local{% endif %}/etc/ipsec.d/cacerts/ca.pem"
      key: "{{ lookup('file', 'certs/' + project_environment + '/root_pub.pem') }}"
