---
- name: trombik.tmux
  version: 1.1.1
- name: trombik.vim
  version: 1.1.1
- name: trombik.zsh
  version: 1.1.1
- name: trombik.hostname
  version: 1.0.1
- name: trombik.hosts
  version: 1.2.1
- name: trombik.x509-certificate
  version: 1.1.1
- name: trombik.sysctl
  version: 1.0.1
- name: trombik.ipfw
  version: 1.0.0
- name: trombik.strongswan
  version: 1.0.0
