---

- name: Install x509_certificate_packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ x509_certificate_packages }}"

- name: Install x509_certificate_additional_packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ x509_certificate_additional_packages }}"
