---
# tasks file for ansible-role-sysctl

- include_vars: "{{ ansible_os_family }}.yml"

- name: Apply sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  with_dict: "{{ sysctl }}"
