---

- name: Install zsh
  yum:
    name: "{{ zsh_package }}"
    state: present

- name: Install zsh_additional_package
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ zsh_additional_packages }}"
