---

- name: Install zsh
  openbsd_pkg:
    name: "{{ zsh_package }}"
    state: present

- name: Install zsh_additional_package
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items: "{{ zsh_additional_packages }}"
